version: '3.8'

services:
  app:
    build:
      context: ./app-files
      dockerfile: app-dockerfile
    container_name: app
    image: app:latest
    volumes:
      - "./:/var/www/html"
      - "./storage/logs:/var/log/apache2"
    ports:
      - 8080:80
