version: '3.8'

services:
  application:
    build:
      context: ./app-files
      dockerfile: app-dockerfile
    container_name: application
    image: laravel-application:latest
    volumes:
      - "./:/var/www/html"
      - "./storage/logs:/var/log/apache2"
    ports:
      - 8080:80
    networks:
      - laravel
    depends_on:
      - "database"
  database:
    build:
      context: ./db-files
      dockerfile: db-dockerfile
    container_name: database
    image: laravel-database:latest
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
